#!/bin/sh

echo -n "Please enter the category: "
read category

echo -n "Please enter the package: "
read package

echo -n "Please set use FLAGS: "
read uses

export USE_PATH="/etc/portage/package.use"

doas mkdir -p ${USE_PATH}/${category}
echo "${category}/${package} ${uses}" | doas tee -a "${USE_PATH}/${category}/${package}"
